name: hola-actions

run-name: ¡GitHub Actions!

on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run script
        run: python holaMundo.py
